profiles:
  - AdministratorAccess-860377398420
  - AdministratorAccess-203562618900
  - AdministratorAccess-920077690180
  - AdministratorAccess-520888687034
  - AdministratorAccess-013358499323
  - AdministratorAccess-429648923701
  - AdministratorAccess-726064475931
  - AdministratorAccess-338101373134
  - AdministratorAccess-137790490477
  - AdministratorAccess-626046454625
  - AdministratorAccess-354961631207
  - AdministratorAccess-105173791259
  - AdministratorAccess-070744430225
  - AdministratorAccess-357736309526
  - AdministratorAccess-458168469311
  - AdministratorAccess-753029861475
  - AdministratorAccess-324828470297
  - AdministratorAccess-296879874673
  - AdministratorAccess-767513147512
regions:
  - us-east-1
  - us-east-2
